     import React from "react"
    const API_DATA=[
        {id:'1',
         title:"DNK Blue Shoes",
         image:'https://i.postimg.cc/j2LCxKbG/sports-shoe1-600x600.jpg',
         image:['https://i.postimg.cc/j2LCxKbG/sports-shoe1-600x600.jpg','https://i.postimg.cc/QCJsZyBR/sports-shoe2.jpg','https://i.postimg.cc/hj4fYT34/sports-shoe4-600x600.jpg','https://i.postimg.cc/NMN5vFW6/sports-shoe5-600x600.jpg'],
         category:'women',
         description: 'Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.',
         price:'450', 
         special:true,
         color:["red","green","yellow"]
        },
        {id:'2',
         title:"Black Tshirt/Shorts",
          image:[],
          
         category:'men',
         description: 'Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.',
         price:'550' ,
         color:["red","green","yellow"],
        },
        {id:'3',
         title:"Casual Regular Sleeves",
         image:"https://i.postimg.cc/sftWyP3n/3xl-dlnxwtop02pista-dlanxa-original-imagpzgfaur78cqc.jpg",
         category:'women',
         description: 'Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.',
         price:'350' ,
         special:true,
         color:["red","green","yellow"],
         image:[''],
          
        },
        {id:'4',
         title:"White Tshirt/Shorts",
         image:"https://postimg.cc/SYYp5HQJ",
         category:'men',
         description: 'Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.',
         price:'450',
         color:["red","green","yellow"], 
         image:[''],
          
        },
        {id:'5',
         title:"Casual Regular Sleeves",
         image:"https://i.postimg.cc/QNWB6Bcc/s-metro-ma125-metronaut-original-imagwkgfyjt4hshs.jpg",
         category:'women',
         description: 'Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.',
         price:'550',
         color:["red","green","yellow"], 
        image:[''],
          
        },
        {id:'6',
         title:"Flora Print Black Tshirt",
         image:"https://i.postimg.cc/qqRH565y/714-Ar-Oo-RSGL-AC-UL320.jpg",
         category:'men',
         description: 'Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.',
         price:'550', 
         special:true,
         color:["red","green","yellow"],
         image:[''],
          
        },
        
        {id:'7',
         title:"Blue Tshirt/Shorts",
         image:"https://i.postimg.cc/QN43WSFb/7177-MS5n-Ff-L-AC-UL320.jpg",
         category:'men',
         description: 'Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.',
         price:'350',
         color:["red","green","yellow"], 
         image:[''],
          
        },

        {id:'8',
         title:"Pink Top",
         image:"https://i.postimg.cc/YqzCVQ0L/xxl-sftops41658-sassafras-curve-original-imagwkf7pjqheqbw.jpg",
         category:'women',
         description: 'Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.',
         price:'550' ,
         special:true,
         color:["red","green","yellow"],
         image:[''],
          
        },
         
        {id:'9',
         title:"White Tshirt/shorts",
         image:"https://i.postimg.cc/yY88MkZf/71f-MBy-Z0rc-L-AC-UL640-QL65.jpg",
         category:'men',
         description: 'Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.',
         price:'250' ,
         color:["red","green","yellow"],
         image:[''],
          
        },


        {id:'10',
         title:"Half Sleeves Blue",
         image:"https://i.postimg.cc/hjNXDgRJ/m-ma234-coffee-bite-original-imahy2uzeehntexs.jpg",
         category:'women',
         description: 'Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.',
         price:'350' ,
         color:["red","green","yellow"],
         image:[''],
          
         special:true,
        },
        {id:'11',
         title:"Red Top",
         image:"https://i.postimg.cc/QdDWKX91/m-mcaw17tp08-79-180-miss-chase-original-imafy4jg7w5gwghr.jpg",
         category:'women',
         description: 'Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.',
         price:'350',
         color:["red","green","yellow"],
         image:[''],
          
         
        },
        {id:'12',
        title:"White Tshirt/shorts",
        image:"https://i.postimg.cc/VLZkmm9z/61l6-VZub3u-S-AC-UL320.jpg",
        category:'men',
        description: 'Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.',
        price:'650',
        color:["red","green","yellow"], 
        image:[''],
          
        
       },
        {id:'13',
         title:"Violet Top",
         image:"https://i.postimg.cc/hjXJRv6W/m-gr6220a-purple-harpa-original-imagcgxtbahbfsrg.jpg",
         category:'women',
         description: 'Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.',
         price:'450' ,
         special:true, 
         color:["red","green","yellow"],
         image:[''],
          
        },
        {id:'14',
        title:"Red Tshirt/shorts",
        image:"https://i.postimg.cc/C5LwpQzZ/71-S7j4r-Vf-ZL-AC-UL320.jpg",
        category:'men',
        description: 'Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.',
        price:'650',
        color:["red","green","yellow"], 
        image:[''],
          
       },
        {id:'15',
        title:"Pink Top",
        image:"https://i.postimg.cc/RZTJcjK8/l-gr6468-pink-harpa-original-imagmwc845wbzyzy.jpg",
        category:'women',
        description: 'Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.',
        price:'850' ,
        special:true, 
        color:["red","green","yellow"],
        image:[''],
          
       },

       {id:'16',
        title:"Black Top",
        image:"https://i.postimg.cc/DzMZ6FZC/xl-prw-m-462-metronaut-original-imagybkgrfpcg3fr.jpg",
        category:'women',
        description: 'Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.',
        price:'250',
        color:["red","green","yellow"], 
        image:[''],
          
       },
       {id:'17',
       title:"Brown Tshirt/shorts",
       image:"https://i.postimg.cc/g26mpRkK/81fp-M7-KUNL-AC-UL320.jpg",
       category:'men',
       description: 'Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.',
       price:'750' ,
       special:true, 
       color:["red","green","yellow"],
       image:[''],
          
      },
       {id:'18',
        title:"Black Kurti",
        image:"https://i.postimg.cc/MptXc18J/xl-142-ramratan-original-imagt8a7nxpsv65k.jpg",
        category:'women',
        description: 'Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.',
        price:'650',
        color:["red","green","yellow"], 
        image:[''],
          
       },
       {id:'19',
       title:"Flora Tshirt/shorts",
       image:"https://i.postimg.cc/9FkCs1VM/81ehk-De4-WL-AC-UL320.jpg",
       category:'men',
       description: 'Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.',
       price:'750' ,
       special:true, 
       color:["red","green","yellow"],
       image:[''],
          
      },
       {id:'20',
        title:"Black Flora Print",
        image:"https://i.postimg.cc/rsWKzbqf/m-gr6445a-black-harpa-original-imagmwc9nrhf8hvb.jpg",
        category:'women',
        description: 'Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.',
        price:'950' ,
        special:true, 
        color:["red","green","yellow"],
        image:[''],
          
       },
       {id:'21',
        title:"Black Full Sleeves",
        image:"https://i.postimg.cc/9MwfNSwc/xl-zip-top-toolook-original-imagum7kmna6zyyb.jpg",
        category:'women',
        description: 'Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.',
        price:'950',
        color:["red","green","yellow"], 
        image:[''],
          
       },
       {id:'22',
       title:"Black Tshirt/shorts",
       image:"https://i.postimg.cc/tTGgwk3P/61i-LVMv36-L-AC-UL320.jpg",
       category:'men',
       description: 'Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.',
       price:'850',
       color:["red","green","yellow"], 
       image:[''],
          
      },
       {id:'23',
        title:"Blue top",
        image:"https://i.postimg.cc/hjNXDgRJ/m-ma234-coffee-bite-original-imahy2uzeehntexs.jpg",
        category:'women',
        description: 'Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.',
        price:'250',
        color:["red","green","yellow"],
        image:[''],
          

       },
       {id:'24',
       title:"Green Shirt/Shorts",
       image:"https://i.postimg.cc/pdbxLTmM/81YBgzoNnoL._AC_UL320_.jpg",
       category:'men',
       description: 'Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.',
       price:'850',
       color:["red","green","yellow"], 
       image:[''],
          
      },
       {id:'25',
        title:"Maroon top",
        image:"https://i.postimg.cc/X7SrtVgm/s-metro-ma192-metronaut-original-imagwkgfphrhz4zx.jpg",
        category:'women',
        description: 'Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.',
        price:'850',
        color:["red","green","yellow"],
        image:[''],
          
       },
       {id:'26',
       title:"Flora Tshirt",
       image:"https://i.postimg.cc/Zqpb8NGq/71-Jjksm-Wxq-L-AC-UL320.jpg",
       category:'men',
       description: 'Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.',
       price:'950',
       color:["red","green","yellow"], 
       image:[''],
          
      },
       {id:'27',
        title:"Red Tshirt",
        image:"https://i.postimg.cc/QdDWKX91/m-mcaw17tp08-79-180-miss-chase-original-imafy4jg7w5gwghr.jpg",
        category:'women',
        description: 'Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.',
        price:'850' ,
        color:["red","green","yellow"],
        image:[''],
          
        
       },
       {id:'28',
       title:"Flora Tshirt",
       image:"https://i.postimg.cc/4yLsfQ9W/71w4fpa-AAf-L-AC-UL320.jpg",
       category:'men',
       description: 'Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.',
       price:'950', 
       color:["red","green","yellow"],
       image:[''],
          
      },
      {id:'29',
      title:"Sliver Ring",
      image:"https://i.postimg.cc/wTXnQVvZ/giva_silver_925_silver_stone-studded_heritage_ring.jpg",
      category:'women',
      item:'accesories',
      description: 'Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.',
      price:'150',
      color:["red","green","yellow"], 
      image:[''],
          
     },
     {id:'30',
      title:"Pearl Necklace",
      image:"https://i.postimg.cc/rpPHwZn0/giva_silver_women_sterling_silver_radiant_pearl_necklace.jpg",
      category:'women',
      item:'accesories',
      description: 'Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.',
      price:'250', 
      color:["red","green","yellow"],
      image:[''],
          
     },
     {id:'31',
      title:"Gold Necklace",
      image:"https://i.postimg.cc/Mpt4hp1Y/shining_diva_gold-toned_&_white_rrsd8047b_gold-plated_crystal-studded_pearl_bracelet.jpg",
      category:'women',
      item:'accesories',
      description: 'Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.',
      price:'550', 
      color:["red","green","yellow"],
      image:[''],
          
     },
     {id:'32',
      title:"Rose Gold Bangles",
      image:"https://i.postimg.cc/9fMSVHpH/shining_diva_rose_gold-toned_9574b_rose_gold-toned_stone_&_pearl-studded_bracelet.jpg",
      category:'women',
      item:'accesories',
      description: 'Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.',
      price:'550', 
      color:["red","green","yellow"],
      image:[''],
          
     },
     {id:'33',
      title:"Sliver Ring",
      image:"https://i.postimg.cc/y87tQZ3d/giva_silver_925_silver_vintage_ring.jpg",
      category:'women',
      item:'accesories',
      description: 'Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.',
      price:'550', 
      color:["red","green","yellow"],
      image:[''],
          
     },
     {id:'34',
      title:"Sliver Ring",
      image:"https://i.postimg.cc/wT17t1j1/fashion_frill_silver_soldier_skull_cocktail_ring.jpg",
      category:'men',
      item:'accesories',
      description: 'Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.',
      price:'350', 
      color:["red","green","yellow"],
      image:[''],
          
     },
     {id:'35',
      title:"Sliver Ring",
      image:"https://i.postimg.cc/y6QDYmsq/thrillz_silver-toned_silver-plated_cocktail_ring.jpg",
      category:'men',
      item:'accesories',
      description: 'Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.',
      price:'350', 
      color:["red","green","yellow"],
      image:[''],
          
     },
     {id:'36',
      title:"Gold Ring",
      image:"https://i.postimg.cc/qvnqLWn0/myki_gold-toned_stone-studded_cocktail_ring_(1).jpg",
      category:'men',
      item:'accesories',
      description: 'Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.',
      price:'550', 
      color:["red","green","yellow"],
      image:[''],
          
     },
     {id:'37',
      title:"Gold Ring",
      image:"https://i.postimg.cc/Fsw10hYD/myki_gold-toned_stone-studded_cocktail_ring.jpg",
      category:'men',
      item:'accesories',
      description: 'Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.',
      price:'550', 
      color:["red","green","yellow"],
      image:[''],
          
     },
     {id:'38',
      title:"Black Shades",
      image:"https://i.postimg.cc/5yRy7Vn9/vincent_chase_black_unisex_uv_protected_wayfarer_sunglasses_-vc_s14525.jpg",
      category:'men',
      item:'accesories',
      description: 'Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.',
      price:'450', 
      color:["red","green","yellow"],
      image:[''],
          
     },
     {id:'39',
      title:"Black Shades",
      image:"https://i.postimg.cc/yxdWydhr/vincent_chase_gunmetal_unisex_uv_protected_sunglasses_-vc_s14506.jpg",
      category:'men',
      item:'accesories',
      description: 'Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.',
      price:'450', 
      color:["red","green","yellow"],
      image:[''],
          
     },
    ]
  export default API_DATA;